readme.md
Implements the abstract method `createsApplication()` in `Laravel\BrowserKitTesting\TestCase`
=> Added use CreatesApplication trait

LICENSE.md
Sync with Dusk and the framework repos.
=> Update and rename LICENSE.txt to LICENSE.md

src/Concerns/InteractsWithPages.php
#16 
Made the styling changes to align with the framework.
=> Fix array multi file upload

src/TestCase.php
https://github.com/laravel/framework/commit/79c6f6774eecf77aef8ed5e2f270551a6f378f1d
=> Add RefreshDatabase trait compatibility

src/TestCase.php
Sync with setUpTraits with framework TestCase https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Testing/TestCase.php#L123
=> Return $uses on setUpTraits

src/TestCase.php
Similar fix to the one made in laravel/framework here https://github.com/laravel/framework/pull/20606
=> count mockery expectations as assertions

composer.json
=> [WIP] Make v4 phpunit 7

src/Constraints/HasElement.php, src/Constraints/HasInElement.php, src/Constraints/HasLink.php, src/Constraints/HasSource.php, src/Constraints/HasText.php, src/Constraints/HasValue.php, src/Constraints/IsChecked.php, src/Constraints/IsSelected.php, src/Constraints/PageConstraint.php, src/Constraints/ReversePageConstraint.php
I decided to continue @GrahamCampbell 's work (#43).
Everything works fine to me and should be ready to release as v4.
=> Update signatures for PHPUnit7

readme.md
This is an exact copy from Laravel 5.3 documentation, see <https://laravel.com/docs/5.3/application-testing>
=> Port over "Application Testing" docs

src/Concerns/InteractsWithPages.php
This new method count elements in the DOM.
For example:
On the view:
```html
<!DOCTYPE html>
<html>
<head>
<title>Example</title>
<link rel="stylesheet" type="text/css" href="{{ asset('css/app.css') }}">
</head>
<body>
<div class="container">
@foreach($users as $user) 
<div class="card-user">
<div class="card-title">{{ $user->full_name }}</div>
<div class="card-body">All info of user</div>
<div class="card-footer">
<a href="#" class="btn btn-primary">Edit</a>
</div>
</div>
@endforeach
</div>
</body>
</html>
```
On the Test:
```php
<?php
namespace Tests\Feature\Auth;
use App\User;
use Tests\TestCase;
class AuthenticationTest extends TestCase
{
/** @test */
public function verify_list_users($role)
{
// HAVING... A ADMIN AND 3 USERS
$admin = factory(User::class)->create(); …
```
=> New method countElements

readme.md
Add syntax highlighting
See the result here - https://github.com/JayBizzle/browser-kit-testing/tree/4.0
=> Prettify Readme

composer.json, phpunit.xml, tests/TestCase.php, tests/Unit/MakesHttpRequestsTest.php
I added unit tests for the trait MakesHttpRequest, but it doesn't cover all its
methods.
Covered methods: `type`, `check`, `uncheck`, `attach`, `select`, `storeInput`, `getForm`, `fillForm`, 
Changes to be committed:
modified:    composer.json
new file: phpunit.xml
new file: tests/TestCase.php
new file: tests/Unit/MakesHttpRequestsTest.php
=> Creation of Unit Testing

src/Concerns/MocksApplicationServices.php
Fixes a minor typo in `MocksApplicationServices::expectsNotification`.
=> [4.0] Fix typo in expectsNotification.

.travis.yml
Will still need to configure Travis for this repo.
=> [4.0] Test with Travis

tests/Unit/MakesHttpRequestsTest.php
I added unit tests for the trait MakesHttpRequest, but it doesn't cover all its
methods.
Covered methods: `assertResponseStatus`, `assertResponseOk`,
`seeStatusCode`, `assertPageLoaded`
Change to be committed:
modified:     tests/Unit/MakesHttpRequestsTest.php
=> [4.0] Adding unit testing

composer.json
The following dependencies will be added:
- ext-dom
- ext-json
- illuminate/database
- illuminate/http
- symfony/console
- symfony/http-kernel
Please, see issue #78
=> Adding dependencies

tests/Unit/ImpersonatesUsersTest.php, tests/Unit/InteractsWithConsoleTest.php, tests/Unit/InteractsWithContainerTest.php, tests/Unit/InteractsWithDatabaseTest.php, tests/Unit/InteractsWithSessionTest.php
I added unit test for the trait `ImpresonatesUsersTest,`
`InteractsWithConsoleTest`, `InteractsWithContainerTest`,
`InteractsWithDatabaseTest`, `InteractsWithSessionTest` (completed coverage)
On branch unit-test
Changes to be committed:
new file:   tests/Unit/ImpersonatesUsersTest.php
new file:   tests/Unit/InteractsWithConsoleTest.php
new file:   tests/Unit/InteractsWithContainerTest.php
new file:   tests/Unit/InteractsWithDatabaseTest.php
new file:   tests/Unit/InteractsWithSessionTest.php
=> [4.0] Completed Coverage to 5 traits

composer.json, readme.md
So we don't need to update it with every single release.
=> [4.0] Use general phrasing for package description

tests/Unit/InteractsWithExceptionHandlingTest.php
I completed the coverage of the unit tests to InteractsWithExceptionHandling
=> [5.0] Completed coverage on InteractsWithExceptionHandling

tests/Unit/InteractsWithPagesTest.php
I added new unit testing to *InteractsWithPages* trait
=> Adding news methods of unit testing

composer.json
Updated Symfony Components to support ^5.0 to resolve #113
=> Add Symfony 5 component support

composer.json
Reverts laravel/browser-kit-testing#114
=> Revert "Add Symfony 5 component support"

src/Concerns/MakesHttpRequests.php
=> Correctly displays expected and actual values.

composer.json
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
=> [7.x] Allow to install Laravel 8.

README.md
Updates the readme to the same style as other readmes with docs.
=> [6.x] Generalize readme

.github/workflows/tests.yml, composer.json
=> [6.x] PHP 8 Support

.github/workflows/tests.yml
=> [6.x] Use ubuntu-18.04

.github/workflows/tests.yml, composer.json, tests/Stubs/OutputStub.php
=> Laravel 9 support
