- src/Concerns/MocksApplicationServices.php
Fix this error
```
BadMethodCallException: Method Mockery_0_Illuminate_Contracts_Events_Dispatcher::dispatch() does not exist on this mock object
```
when using `$this->expectsEvents(MyEvent::class)`
> Add missing mock for dispatch method

- composer.json
I don't see that this package would have a 6 month release cycle so there no reason to lock it right now.
Signed-off-by: crynobone <crynobone@gmail.com>
> Allow anything between 3.1 to <4.0 to be installed.

- src/Concerns/MocksApplicationServices.php
We encountered the `BadMethodCallException: Method Mockery_0_Illuminate_Contracts_Bus_Dispatcher::getCommandHandler() does not exist on this mock object` exception when trying to update the company app to Laravel 5.4. 
Adding this method to the mock object on the `MocksApplicationServices` class solved the problem.
> Adding `getCommandHandler` to events and jobs mock

- src/Concerns/MakesHttpRequests.php
Not a new issue, this fix has already been done in Laravel 5.3
[5.3] Fix seeJsonStructure for empty response #16642
https://github.com/laravel/framework/pull/16642/commits/6ea6e22e77bb66446de18b0ed5b22141a75ba204
> Fix seeJsonStructure for empty response

- src/Concerns/InteractsWithPages.php
- src/Concerns/InteractsWithSession.php
- src/Concerns/MakesHttpRequests.php
- src/Constraints/FormFieldConstraint.php
- src/Constraints/HasValue.php
- src/Constraints/IsSelected.php
- src/Constraints/PageConstraint.php
- src/HttpException.php
Related issue: https://github.com/laravel/browser-kit-testing/issues/13
PHPUnit 5.x is not supported anymore with those changes so it should be tagged as major release if accepted.
> Support for PHPUnit 6.x

- composer.json
Should we as well require `"phpunit/phpunit": "~6.0"`?
> Bump version for PHPUnit 6.x release

- composer.json
To prevent people from installing browser-kit-testing 2.x with PHPUnit 5.7.
See https://github.com/laravel/browser-kit-testing/issues/13
> Add PHPUnit as required dependency

- src/Concerns/InteractsWithSession.php
seeInSession was marked as returning void when it always returns $this.
> Add correct return type to seeInSession

- src/Concerns/InteractsWithExceptionHandling.php
- src/TestCase.php
This is ported from `laravel/framework`'s `Illuminate\Foundation\Testing\TestCase` to allow users to swap the `Illuminate\Contracts\Debug\ExceptionHandler` for a better testing experience.
> Add withoutExceptionHandling method for testing.

- src/Concerns/InteractsWithExceptionHandling.php
Not following the PSR autoload namespacing used by all the other files. 
Causes error "Trait 'Laravel\BrowserKitTesting\Concerns\InteractsWithExceptionHandling'"
> Fixes InteractsWithExceptionHandling Namespacing

- src/Concerns/MocksApplicationServices.php
Using phpunit 6 and browser-kit-testing >= 2.0.1 if a test only uses the expects methods provided by MocksApplicationServices the test will be marked as risky because it not perform any assertions.
> Add assertions to avoid the risky tests label in phpunit 6

- src/Concerns/MakesHttpRequests.php
This is more of a *nice to have*, rather than an issue.
Currently, `assertRedirectedTo` checks that the response is an instance of `Illuminate\Http\RedirectResponse`. This causes tests to fail when returning instances of its parent class, `Symfony\Component\HttpFoundation\RedirectResponse`.
This PR changes the assertion to check that the response is an instance of `Symfony\Component\HttpFoundation\RedirectResponse` to allow for instances of either object to be returned.
> Assert response is Symfony RedirectResponse in assertRedirectedTo

- src/Concerns/MakesHttpRequests.php
The breaking change of 5.6.30 (not serialize cookie values by default) broke the `seeCookie()` method of Browser Kit Testing. This PR fixes this.
Developers with app below 5.6.30 don't need to do anything. Developers with app 5.6.30+ need to update their tests like so:
```php
// true is for encrypted (default value)
// false is for not unserializing (this fixes the test)
$this->seeCookie('name', 'value', true, false);
```
> Add $unserialize param to fix breaking change of 5.6.30

- src/Concerns/MocksApplicationServices.php
Change expect fire to expect dispatch.
I'm fairly certain this change is needed to stay compatible with this change in Laravel framework release 5.7.4:
https://github.com/laravel/framework/commit/b298de2cf10a9828162d502a1f6b92089aadee18
> [5.7.4] Update MocksApplicationServices to expect dispatch instead of fire.

- src/Concerns/MakesHttpRequests.php
This is just a copy paste from 
`Illuminate\Foundation\Testing\Concerns\MakesHttpRequests::withoutMiddleware`;
> Make it possible to disable a specific middleware

- composer.json
Mockery was absent even though it's a hard dependency of the library. Also cleaned up the compsoser.json file a bit with config settings from other Laravel libraries.
See https://github.com/laravel/browser-kit-testing/issues/41
> [4.0] Require Mockery and cleanup composer.json

- readme.md
"Laravel 5" isn't used anymore on the welcome page so these tests would fail with a fresh Laravel install.
Also used newline syntax for array elements and trailing commas to be in line with the Laravel coding standards.
> [4.0] Cleanup readme

- tests/Unit/InteractsWithAuthenticationTest.php
- tests/Unit/MakesHttpRequestsTest.php
I added unit tests for the trait InteractsWithAuthentication (completed coverage).
Covered methods: `seeIsAuthenticated`, `dontSeeIsAuthenticated`,
`isAuthenticated`, `seeIsAuthenticatedAs`, `seeCredentials`,
`dontSeeCredentials`, `hasCredentials`
Change to be committed:
new file:      tests/Unit/InteractsWithAuthenticationTest.php
modified:      tests/Unit/MakesHttpRequestsTest.php
> Complete coverage on InteractsWithAuthentication

- .gitignore
- .travis.yml
- composer.json
- src/Concerns/InteractsWithPages.php
- src/Concerns/MakesHttpRequests.php
- src/HttpException.php
- tests/Unit/MakesHttpRequestsTest.php
This PR provides compatibility for PHPUnit 8. I managed to do this in a compatible way with PHPUnit 7.0 so there's no major version release needed, only a minor one. I've also updated Travis to test both against PHPUnit 7 and 8.
The only thing that really changed is that `Laravel\BrowserKitTesting\HttpException` isn't an instance of `PHPUnit\Framework\ ExpectationFailedException` anymore. But I don't feel that this change warrants a new major version release.
> [4.0] PHPUnit 8 support

- .gitignore
These belong in a global gitignore or a simply not used in the project.
> [4.0] Remove unnecessary .gitignore lines

- .travis.yml
- composer.json
It turns out that installs of PHPUnit 8 are currently not possible because we override the setUp method and its signature has changed. This commit reverst the ability to install PHPUnit 8 since it won't work anyway.
In a follow-up commit I'll send in support for PHPUnit 8 on the next release branch.
This only requires a patch release.
> [4.0] Prevent installs of PHPUnit 8

- composer.json
This is critical to allow developers to test against the nightly Laravel version even if it's not stable yet. Imagine developing Laravel Framework 5.9.0 when `orchestra/testbench-core` doesn't even support it.
> [6.0] Always has a version to support upcoming version

- src/Concerns/InteractsWithExceptionHandling.php
- tests/Stubs/ExceptionHandlerStub.php
- tests/Stubs/OutputStub.php
- tests/Unit/InteractsWithExceptionHandlingTest.php
- tests/Unit/InteractsWithSessionTest.php
I added unit test for the trait `InteractsWithExceptionHandling,` `InteractsWithSession` (completed coverage)
On branch test-session-exception
Changes to be committed:
new file:   tests/Stubs/ExceptionHandlerStub.php
new file:   tests/Stubs/OutputStub.php
new file:   tests/Unit/InteractsWithExceptionHandlingTest.php
modified:   tests/Unit/InteractsWithSessionTest.php
> [5.0] Completed Coverage to 2 traits

- src/Concerns/InteractsWithPages.php
This pull request makes `followRedirects` keep the cookies from the response when requesting to the new location.
I think the follow redirects should behave as browsers and all modern browsers keep the cookies after a redirect.
The changes should not break any existing code, but I am open to make it configurable via opt-in.
> [6.0] Keep cookies between redirects

- .styleci.yml
Alpha ordered imports will become the default for the laravel preset in a few minutes time on styleci.io.
> [5.0] Update .styleci.yml

- .travis.yml
- composer.json
- src/Concerns/InteractsWithExceptionHandling.php
- src/Concerns/InteractsWithPages.php
- tests/Stubs/ExceptionHandlerStub.php
- tests/Unit/InteractsWithPagesTest.php
This PR:
- Updates Symfony to 5.0
- Drops support for Laravel 6.x
- Drops support for PHPUnit 7
> [6.x] Symfony 5 support

- src/Concerns/MakesHttpRequests.php
Initially it was marked to be removed in 5.0 but might have been forgotten.
> [6.x] Remove deprecated method so we don't have to deal with assertArraySubset.

- composer.json
- src/Concerns/MakesHttpRequests.php
- src/TestResponse.php
- tests/Unit/MakesHttpRequestsTest.php
All HTTP tests will now return an instance of `Laravel\BrowserKitTesting\TestResponse` instead of `Illuminate\Http\Response`. The advantage of having TestResponse is that you have access to every assertion available in [Laravel HTTP Tests > Response Assertions](https://laravel.com/docs/master/http-tests#response-assertions).
------
This PR no longer add any breaking change. Old and new methods can be used.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [6.x] Utilise illuminate/testing based on #122

- src/Concerns/MakesHttpRequests.php
- src/TestResponse.php
My bad, just found it out while testing my packages with dev-master
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [6.x] Fix invalid Illuminate\Testing\Assert import

- src/Concerns/MakesHttpRequests.php
- tests/Unit/MakesHttpRequestsTest.php
Copied laravel/framework#30101 here
> [5.x] Copied #30101

- src/Concerns/MakesHttpRequests.php
Disable unserialize by default since laravel no longer serializes cookies by default.
Make sure the cookie prefix is removed before asserting the value.
> [5.x] Remove cookie prefix in seeCookie

- tests/Unit/InteractsWithConsoleTest.php
- tests/Unit/InteractsWithDatabaseTest.php
- tests/Unit/InteractsWithPagesTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assertion equals checking strict.
> Improve assertions

- src/Concerns/MakesHttpRequests.php
This PR fixes the usage of the `withCookie()` / `withCookies()` methods. See error below:
```
Class 'Laravel\BrowserKitTesting\Concerns\CookieValuePrefix' not found
at vendor/laravel/browser-kit-testing/src/Concerns/MakesHttpRequests.php:695
691|             return array_merge($this->defaultCookies, $this->unencryptedCookies);
692|         }
693| 
694|         return collect($this->defaultCookies)->map(function ($value, $key) {
> 695|             return encrypt(CookieValuePrefix::create($key, app('encrypter')->getKey()).$value, false);
696|         })->merge($this->unencryptedCookies)->all();
697|     }
698| 
699|     /**
```
> [6.x] Add missing import for CookieValuePrefix

- src/Concerns/MakesHttpRequests.php
Response-object originates from `TestResponse::fromBaseResponse()` call
which returns "self".
In this case it means that `\Laravel\BrowserKitTesting\TestResponse`
class would always be used.
This should solve some of the issues reported by PhpStAn.
related to #149
p.s. is it a policy to close issues before fix is provided? seems to discourage discussion. at least that's how it worked for me :-(
> [6.x] Use TestResponse as return value in PHPDoc

- src/Concerns/MakesHttpRequests.php
The `$cookies` variable wasn't passed to `->call(...)` in the `get()` and `json()` methods. This PR fixes it.
> Fix missing $cookies argument

- src/Concerns/MakesHttpRequests.php
> Fix seeJson with null data

- .github/workflows/tests.yml
By throwing deprecations in the test suite, we can solve them early-on.
> [6.x] Throw deprecations in test suite

- src/Concerns/MakesHttpRequests.php
PHPStan complains when an argument other than `null` is provided to the `withoutMiddleware([Foobar::class]);` method.
> Fix withoutMiddleware docblock

- .github/workflows/tests.yml
- composer.json
Drops Laravel below v10 and PHP below v8.1 to prepare for PHPUnit v10 support.
> [7.x] Drop old PHP and Laravel versions
